### ISSUE TITLE
table template a-table-column-group （#3934， ＃3938）

### ISSUE THREAD

**Issue by runkobe24** [vueComponent/ant-design-vue#3966] opened 2021-04-19 17:07 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
vue3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/pull/3938](https://github.com/vueComponent/ant-design-vue/pull/3938)

### Steps to reproduce
Still not implemented

### What is expected?
a-table-column can use v-for in a-table-column-group

### What is actually happening?
a-table-column using v-for in a-table-column-group will result in empty dom

**Comment by runkobe24** [comment] 2021-04-19 17:11
<a-table :data-source="data" bordered>

    <a-table-column-group>
      <template #title><span style="color: #1890ff">Name</span></template>
      //这是成功的
      <a-table-column key="firstName" data-index="firstName">
        <template #title><span style="color: #1890ff">First Name</span></template>
      </a-table-column>
      //这是失败的
      <a-table-column v-for="item in 3" :key="item" :title="item" :data-index="item" />
    </a-table-column-group>
    <a-table-column key="age" title="Age" data-index="age" />
    <a-table-column key="address" title="Address" data-index="address" /> 
  
  </a-table>

**Comment by John60676** [comment] 2021-04-20 02:30
已经修复了，等发版

**Comment by John60676** [comment] 2021-04-20 02:31
Duplicate of #3934

**Closed by John60676** 2021-04-20 02:31 UTC
