### ISSUE TITLE
select在IE存在闪动

### ISSUE THREAD

**Issue by letVV** [vueComponent/ant-design-vue#2232] opened 2020-05-13 08:36 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
ie浏览器

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/new?template=----please-use-new-issue-ant-design-vue---.md](https://github.com/vueComponent/ant-design-vue/issues/new?template=----please-use-new-issue-ant-design-vue---.md)

### Steps to reproduce
select下拉列表是在body下创建的,body被撑开的滚动条是没问题的,但是body有子元素div,并且这个div的height固定,还设置了overflow:auto,当这个div产生滚动条,里面使用select就有闪屏问题

### What is expected?
无闪屏

### What is actually happening?
闪屏

**Comment by letVV** [comment] 2020-05-13 09:14
body出现滚动条不会闪动,但是body里面的子元素存在滚动条,点击select就有闪动,初步认为是select的下拉列表创建在body影响的

**Comment by hy08** [comment] 2020-07-02 07:39
出现同样的问题，ie11环境下，祖先元素设置overflow:auto,无论是Select还是Modal都会导致页面重绘

**Comment by hy08** [comment] 2020-08-03 09:13
期待这个bug的解决

**Comment by xrkffgg** [comment] 2020-08-03 09:37
Duplicate of https://github.com/ant-design/ant-design/issues/21039

**Closed** 2020-08-05 03:32 UTC
