### ISSUE TITLE
官网 全局化配置 选择中文后, 星期跟月显示错误

### ISSUE THREAD

**Issue by stevieyu** [vueComponent/ant-design-vue#3526] opened 2021-01-12 10:33 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
mac 11.2  chrome 78

### Reproduction link
[https://2x.antdv.com/components/config-provider-cn/](https://2x.antdv.com/components/config-provider-cn/)

### Steps to reproduce
打开官网, 选择全局化配置, 选择中文

### What is expected?
星期跟月份正常显示中文

### What is actually happening?
星期跟月份显示成英文

**Comment by John60676** [comment] 2021-01-13 01:10
Duplicate of #2527

**Closed** 2021-01-16 03:00 UTC
