### ISSUE TITLE
a-button点击后报错

### ISSUE THREAD

**Issue by yanggengzhen123** [vueComponent/ant-design-vue#7137] opened 2023-11-24 09:12 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
Vue version 3.3.4  "ant-design-vue": "4.0.7",

### Reproduction link
[https://www.antdv.com/components/button-cn](https://www.antdv.com/components/button-cn)

### Steps to reproduce
a-button点击后报错

### What is actually happening?
<a-button type="primary">Loading</a-button>
点击后报错
useConfigInject.js:64 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
at ReactiveEffect.fn (useConfigInject.js:64:83)
at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
at get value [as value] (reactivity.esm-bundler.js:1135:33)
at showWave (useWave.js:7:21)
at HTMLButtonElement.onClick (index.js:51:13)

**Comment by kovsu** [comment] 2023-11-24 09:30
Duplicate of #7106
可以先用 4.0.6，等 #7108 合并应该就好了

**Closed by kovsu** 2023-11-24 09:30 UTC

**Comment by tetap** [comment] 2023-11-24 09:46
发版本不哥们。退回4.0.6   Space 重复 Key 问题看着也很难受

**Comment by kKevin0001** [comment] 2023-12-12 06:21
我也遇到了这个问题，并且在一台电脑不报错，在另一台电脑会报错
