### ISSUE TITLE
add dark.less and compact.less as antd-react

### ISSUE THREAD

**Issue by Yovven** [vueComponent/ant-design-vue#3039] opened 2020-10-25 08:04 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
to switch between light and dark themes dynamically

### What does the proposed API look like?
参照antd-react

**Comment by xrkffgg** [comment] 2020-11-04 03:30
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/2768

**Closed by xrkffgg** 2020-11-04 03:30 UTC
