### ISSUE TITLE
cascader type definition error

### ISSUE THREAD

**Issue by chengdick** [vueComponent/ant-design-vue#3936] opened 2021-04-13 10:17 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
window 谷歌 vue3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/next/components/cascader/index.tsx](https://github.com/vueComponent/ant-design-vue/blob/next/components/cascader/index.tsx)

### Steps to reproduce
vue-tsc --noEmit
执行这个命令报错

generateFilteredOptions(prefixCls: string, renderEmpty: typeof import("../config-provider/renderEmpty").default):
{
[x: string]: any;
__IS_FILTERED_OPTION: boolean;
path: CascaderOptionType[];
disabled: boolean;
} | {
[x: string]: void | JSX.Element;
disabled: boolean;
}[];

### What is expected?
generateFilteredOptions(prefixCls: string, renderEmpty: typeof import("../config-provider/renderEmpty").default):
{
[x: string]: any;
__IS_FILTERED_OPTION: boolean;
path: CascaderOptionType[];
disabled: boolean;
} | {
[x: string]: void | JSX.Element | boolean;
disabled: boolean;
}[];

### What is actually happening?
类型定义报错，

---
vue-tsc --noEmit 执行不了

**Comment by John60676** [comment] 2021-04-13 14:43
Duplicate of #3895

**Closed by John60676** 2021-04-13 14:43 UTC
