### ISSUE TITLE
Vue3 中使用 VNode 的问题（Notifiction、Message）组件

### ISSUE THREAD

**Issue by shanyuhai123** [vueComponent/ant-design-vue#3376] opened 2020-12-16 06:16 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
Windows、Linux

### Reproduction link
[https://2x.antdv.com/components/notification-cn/#components-notification-demo-custom-close-button](https://2x.antdv.com/components/notification-cn/#components-notification-demo-custom-close-button)

### Steps to reproduce
打开官网 https://2x.antdv.com/components/notification-cn/#components-notification-demo-custom-close-button ，点击示例自定义按钮未生效

### What is expected?
正确的样式

### What is actually happening?
返回了函数本身

**Comment by shanyuhai123** [comment] 2020-12-16 06:20
1. 在 2.0 的代码中缺乏了对函数的判断，导致官网发生该问题
2. 我尝试直接在 h 方法中使用 `a-button` 会丢失样式，详情见  https://codesandbox.io/s/fhb9l?file=/src/App.vue
![image](https://user-images.githubusercontent.com/27122409/102312333-76cb7400-3fa9-11eb-9d83-c49b7d4adf5c.png)

3. 而如果在 h 方法中直接使用 `Button` 则可以正确展示，详情   https://codesandbox.io/s/0mk3r?file=/src/App.vue
![image](https://user-images.githubusercontent.com/27122409/102312470-bbefa600-3fa9-11eb-8552-b79562e9cf5f.png)

**Comment by John60676** [comment] 2020-12-16 07:23
Duplicate of #3324

**Closed by John60676** 2020-12-16 07:23 UTC

**Comment by shanyuhai123** [comment] 2020-12-16 07:30
> Duplicate of #3324

还有一个问题时是直接使用 `a-button` 未能正确渲染。

**Comment by John60676** [comment] 2020-12-16 08:16
about `h('a-button') `, refernence:  https://github.com/vuejs/vue-next/issues/1927#issuecomment-678330753
