### ISSUE TITLE
a-textarea 组件赋予 allowClear 属性后，只伸不缩；另置于 a-form-modal-item 组件中，上下调整大小的两个反方向都是拉伸

### ISSUE THREAD

**Issue by suerssk** [vueComponent/ant-design-vue#2563] opened 2020-07-15 09:37 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
windows7 、 Chrome 83.0.4103.116(正式版)(64位)、vue2.6.10

### Reproduction link
[https://www.antdv.com/components/input-cn/#components-input-demo-textarea](https://www.antdv.com/components/input-cn/#components-input-demo-textarea)

### Steps to reproduce
文档的例子就有标题描述的第一点(只伸不缩); 另在 a-form-modal 中，按文档举例的布局效果书写，只要加上 `allowClear` 属性，就出现按下鼠标两个方向移动，只有拉伸 textarea 区域的效果

### What is expected?
能像默认效果一样，伸缩均可

### What is actually happening?
如上面描述的一样，只能单方向拉伸

**Comment by xrkffgg** [comment] 2020-07-15 09:40
Has fixed in https://github.com/vueComponent/ant-design-vue/pull/2530
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/2486

**Closed** 2020-07-15 09:40 UTC
