### ISSUE TITLE
Enter the emoji expression in the input input box, the showCount display is wrong

### ISSUE THREAD

**Issue by suginaMiki** [vueComponent/ant-design-vue#5944] opened 2022-09-02 06:44 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.0

### Environment
win10， Chrome104.0.5112.81， Vue3.2.25

### Reproduction link
[https://www.antdv.com/components/input-cn](https://www.antdv.com/components/input-cn)

### Steps to reproduce
input输入emoji表情，并且显示计数（showCount）

### What is expected?
一个emoji占2个字符，且一个emoji在计数上应该算2

### What is actually happening?
一个emoji占2个字符，且一个emoji在计数上实际是1

---
就在ant官网组件示例里就能重现

**Comment by kovsu** [comment] 2023-09-01 00:58
Duplicate of #6794

**Closed by kovsu** 2023-09-01 00:58 UTC
Labels: enhancement
