### ISSUE TITLE
a-radio-group 取消已选择项后，change事件再也无法触发，也无法再选中

### ISSUE THREAD

**Issue by since2006** [vueComponent/ant-design-vue#3377] opened 2020-12-16 06:17 UTC
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
windows10, chrome 87, vue 2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-design-vue-forked-kpuj4?file=/src/App.vue)

### Steps to reproduce
change事件中，取消当前选中项，再点击时，上一步选中项change事件无法触发

### What is expected?
还能触发change事件，还能继续选中

### What is actually happening?
无法触发change事件，无法继续选中

**Comment by John60676** [comment] 2020-12-16 07:28
Duplicate of #3047

**Closed by John60676** 2020-12-16 07:28 UTC
