### ISSUE TITLE
项目中无文档源码，离线环境如何查看文档，求大神指点

### ISSUE THREAD

**Issue by humbinal** [vueComponent/ant-design-vue#3239] opened 2020-11-22 14:27 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
vue3.0

### Reproduction link
[https://github.com/anncwb/vue-vben-admin/blob/main/CHANGELOG.zh_CN.md](https://github.com/anncwb/vue-vben-admin/blob/main/CHANGELOG.zh_CN.md)

### Steps to reproduce
项目中无文档源码，离线环境如何查看文档，求大神指点

### What is expected?
项目中无文档源码，离线环境如何查看文档，求大神指点

### What is actually happening?
项目中无文档源码，离线环境如何查看文档，求大神指点

**Comment by xrkffgg** [comment] 2020-11-22 14:29
https://github.com/vueComponent/ant-design-vue/issues/2800#issuecomment-688109429

**Comment by xrkffgg** [comment] 2020-11-22 14:29
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/2800

**Closed** 2020-11-22 14:30 UTC

**Comment by humbinal** [comment] 2020-11-22 14:34
好吧，就是没法看了，文档不开源的开源项目有点奇怪，哎。。
