### ISSUE TITLE
下载Release源代码尝试npm install来生成离线文档时出错

### ISSUE THREAD

**Issue by bluemiaomiao** [vueComponent/ant-design-vue#3265] opened 2020-11-27 04:59 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
macOS Big Sur/ Chrome Lastest/Vue 2.x/Vs Code/Nodejs v10.23.0

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/archive/2.0.0-rc.2.tar.gz](https://github.com/vueComponent/ant-design-vue/archive/2.0.0-rc.2.tar.gz)

### Steps to reproduce
```
jackson@JacksondeMBP ant-design-vue-2.0.0-rc.2 % npm install
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14 . Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14  and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! Unexpected end of JSON input while parsing near '...me":1590529431772},"7'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jackson/.npm/_logs/2020-11-27T04_50_09_440Z-debug.log
jackson@JacksondeMBP ant-design-vue-2.0.0-rc.2 %
```

log file content:
```
4517 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...me":1590529431772},"7'
4517 verbose stack     at JSON.parse (<anonymous>)
4517 verbose stack     at parseJson (/Users/jackson/.nvm/versions/node/v10.23.0/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
4517 verbose stack     at consumeBody.call.then.buffer (/Users/jackson/.nvm/versions/node/v10.23.0/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
4517 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
4518 verbose cwd /Users/jackson/Documents/Projects/ant-design-vue-2.0.0-rc.2
4519 verbose Darwin 20.1.0
4520 verbose argv "/Users/jackson/.nvm/versions/node/v10.23.0/bin/node" "/Users/jackson/.nvm/versions/node/v10.23.0/bin/npm" "install"
4521 verbose node v10.23.0
4522 verbose npm  v6.14.8
4523 error Unexpected end of JSON input while parsing near '...me":1590529431772},"7'
4524 verbose exit [ 1, true ]
```

### What is expected?
正确安装依赖
### What is actually happening?
无法实现，其他项目正常。

HELP!!!

**Comment by xrkffgg** [comment] 2020-11-27 05:02
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/2800

**Closed by xrkffgg** 2020-11-27 05:02 UTC
