### ISSUE TITLE
Button type added other color

### ISSUE THREAD

**Issue by vciloglu** [vueComponent/ant-design-vue#2627] opened 2020-07-30 08:49 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
There are very few color options in the buttons. I want more than one color option.

### What does the proposed API look like?
nuxt

**Comment by xrkffgg** [comment] 2020-07-30 09:27
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/1825

**Closed** 2020-07-30 09:28 UTC
