### ISSUE TITLE
DatePicker 日期zh-cn下的月份以及星期都还是英文的

### ISSUE THREAD

**Issue by yajore** [vueComponent/ant-design-vue#2607] opened 2020-07-27 02:26 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
window，chrome laster，vue laster

### Reproduction link
[https://www.antdv.com/components/date-picker-cn/](https://www.antdv.com/components/date-picker-cn/)

### Steps to reproduce
官网的ex也是这样的

### What is expected?
zhCN下月份和星期应是中文

### What is actually happening?
月份和星期使用了英文

**Comment by xrkffgg** [comment] 2020-07-27 02:33
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/2527

**Closed by xrkffgg** 2020-07-27 02:33 UTC

**Comment by yxh410** [comment] 2020-10-29 06:58
我也有这样的问题，估计是moment的问题，当初始值用moment赋值后就不会有英文的，但清空后星期和月份又会变成英文
