### ISSUE TITLE
yarn build bug 

### ISSUE THREAD

**Issue by agoni1212** [vueComponent/ant-design-vue#3932] opened 2021-04-13 02:57 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
vs code

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues](https://github.com/vueComponent/ant-design-vue/issues)

### Steps to reproduce
yarn build

### What is expected?
yarn build success

### What is actually happening?
yarn build failed with error

![image](https://user-images.githubusercontent.com/22545824/114490213-02e36480-9c47-11eb-87d2-a0320866900e.png)

**Comment by John60676** [comment] 2021-04-13 03:14
Duplicate of #3895

**Closed by John60676** 2021-04-13 03:14 UTC
Labels: help wanted
