### ISSUE TITLE
当级联选择，树型选择，穿梭框，时间选择框，选择器，自动完成 等组件出现滚动条时，能把自带的滚动条美化成符合ui规范的样子吗

### ISSUE THREAD

**Issue by dcdlove** [vueComponent/ant-design-vue#3105] opened 2020-11-04 03:04 UTC
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
当这些组件出现浏览器自带滚动条时真的太丑了，直接把ant漂亮的界面打回到解放前，都迭代4个大版本了一直没处理，隔壁element ui早就做了，这个体验真的很重要

### What does the proposed API look like?
全部系统，所有浏览器，vue2，vue3

**Comment by xrkffgg** [comment] 2020-11-04 03:28
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/3071

**Closed by xrkffgg** 2020-11-04 03:28 UTC
