### ISSUE TITLE
Progress component title attribute interferes with tooltip

### ISSUE THREAD

**Issue by btangmu** [vueComponent/ant-design-vue#4929] opened 2021-11-25 16:23 UTC
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
macOS big sur; firefox 94.0.2; whatever vue is running at https://www.antdv.com/components/progress/

### Reproduction link
[https://www.antdv.com/components/progress/](https://www.antdv.com/components/progress/)

### Steps to reproduce
Go to https://www.antdv.com/components/progress/ and look at the demos for "Circular progress bar" and "Progress bar with success segment". Hover on the percentages("75%" and "60%") in the centers of the examples.

### What is expected?
For the "Circular progress bar" there should be no useless duplication of "75%" in a pop-up window when you hover. If a progress component itself has its own more explanatory title attribute, that title should be displayed when you hover, not "75%".

For the "Progress bar with success segment" only the intended tooltip should be displayed, implemented by an "a-tooltip" surrounding the "a-progress".

### What is actually happening?
"Circular progress bar" shows "75%" in a pop-up (which replaces the intended title if there is one).

"Progress bar with success segment" confusingly shows two popup windows at the same time, but possibly in different locations -- both the intended tooltip that is implemented by an "a-tooltip" surrounding the "a-progress", and the useless "60%".

---
The use of a-tooltip in combination with a-progress is important but only one example has it -- "Progress bar with success segment" -- so it's not easy to find; tooltip and success segment being two different things. It would be helpful to call more attention to the recommended (?) usage of  a-tooltip in combination with a-progress.

Also, a-tooltip is inferior to a "title" attribute in one respect: a-tooltip turns newlines into spaces, while title respects newlines.

**Comment by srl295** [comment] 2021-11-30 21:53
@tangjinzhou can you explain the *wontfix*?

**Comment by srl295** [comment] 2021-11-30 22:05
@tangjinzhou opened a PR ^

**Comment by tangjinzhou** [comment] 2022-01-27 02:22
This is a feature, not a bug.
I don't think there's anything wrong with that and could have had better accessibility

**Comment by tangjinzhou** [comment] 2022-01-27 02:22
@srl295

**Comment by srl295** [comment] 2022-01-27 02:53
Hi @tangjinzhou 

> This is a feature, not a bug.

How is it a feature?

Can you explain the benefit of the "title" attribute?



Or; Is there a better way to make the tooltip work? As @btangmu noted, the current behavior is buggy because we cannot see the tooltip clearly. 

Would a screenshot help to show the issue?

> I don't think there's anything wrong with that and could have had better accessibility

It won't bring better accessibility because it's the same text that's already accessible.

**Comment by srl295** [comment] 2022-01-27 02:54
And again thank you for ant dv

**Comment by tangjinzhou** [comment] 2022-01-27 09:14
>  the current behavior is buggy because we cannot see the tooltip clearly

??  

![image](https://user-images.githubusercontent.com/6937879/151328237-b1310e9a-fab8-4127-a1a6-f345e9a2664a.png)

**Comment by srl295** [comment] 2022-01-27 13:58
@tangjinzhou would you accept a PR to make this behavior selectable?

**Comment by tangjinzhou** [comment] 2022-01-28 02:01
Ok, I will add `title` prop to config it

**Closed** 2022-01-28 02:02 UTC
Labels: wontfix

**Comment by agoni1212** [comment] 2022-01-28 02:16
![image](https://user-images.githubusercontent.com/22545824/151475569-a3ba2764-040a-448f-a05e-8cf4bf795698.png)

**Comment by tangjinzhou** [comment] 2022-01-28 02:33
you can update to 3.0.0-beta.9
If you donot need title, you can set `title=''`

**Comment by srl295** [comment] 2022-01-28 16:42
> you can update to 3.0.0-beta.9
> If you donot need title, you can set `title=''`

fyi @btangmu
